<a href="https://colab.research.google.com/github/jagdish-cm/Hinglish_Sentiment_Analysis/blob/master/sentiment_analysis_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from __future__ import print_function
from nltk.metrics import *
import re
import nltk 
import collections
from itertools import groupby
import csv

In [0]:
with open('/content/drive/My Drive/Hinglish/kgp.csv', 'r') as f:
  reader = csv.reader(f)
  kgp_dict = list(reader)
  
kgp_list = []
for sublist in kgp_dict:
    for item in sublist:
        kgp_list.append(item)
        
kgp_list = sorted(set(kgp_list), key=lambda x:kgp_list.index(x))
kgp_list.sort()


with open('/content/drive/My Drive/Hinglish/HInglish-dict.csv', 'r') as f:
  reader = csv.reader(f)
  dictionary = list(reader)
  
flat_list = []
for sublist in dictionary:
    for item in sublist:
        flat_list.append(item)
        
flat_list = sorted(set(flat_list), key=lambda x:flat_list.index(x))
flat_list.sort()


        
with open('/content/drive/My Drive/Hinglish/hing_positive.csv', 'r') as f:
  reader = csv.reader(f)
  positive = list(reader)
  
pos_list = []
for sublist in positive:
    for item in sublist:
        pos_list.append(item)
        
        
pos_list = sorted(set(pos_list), key=lambda x:pos_list.index(x))
pos_list.sort()


with open('/content/drive/My Drive/Hinglish/negative_hinglish.csv', 'r') as f:
  reader = csv.reader(f)
  negative = list(reader)
  
neg_list = []
for sublist in negative:
    for item in sublist:
        neg_list.append(item)
        


neg_list = sorted(set(neg_list), key=lambda x:neg_list.index(x))
neg_list.sort()


        
with open('/content/drive/My Drive/Hinglish/stopwords.csv', 'r') as f:
  reader = csv.reader(f)
  stopw = list(reader)
  
stop_list = []
for sublist in stopw:
    for item in sublist:
        stop_list.append(item)
        
        
8


stop_list = sorted(set(stop_list), key=lambda x:stop_list.index(x))
stop_list.sort()


In [0]:
kgp_list3 = []
for i in kgp_list:
    j = i.replace('\t','')
    kgp_list3.append(j)

In [0]:
corpus = []
with open("/content/drive/My Drive/Hinglish/unbiased_reviews.csv", "r") as dataset1:
    dataset1 = csv.reader(dataset1, delimiter=',')
    next(dataset1)
    for lines in dataset1:
      print(lines)
      
      review = re.sub('[^a-zA-Z]', ' ', lines[0])
      review = review.lower()
      review = review.split()
      corpus.append(review)
      
dataset2 = pd.read_csv("/content/drive/My Drive/Hinglish/HInglish-dict.csv")

['kahaanee ke abhaav me unake vyaktigat prayaas kaa prabhaav kam ho jaataa hai.', '-1']
['nakal ke aarop men vahaan unakee chhantai ho jaatee hai.', '-1']
['usakee vajah se jagahnsai bhee hotee hai.', '-1']
['abcd 2’ me drama ke kamee hai, is kamee kee vajah se hee suru aur vinnee kaa romaans bhee naheen ubhar paataa.', '-1']
['nateejatan donon ke beech kaa romaantik song achaanak aur gairajarooree lagataa hai', '-1']
['kintu khud abhinay karate samay ve niraash karate hain.', '-1']
['unake lie kuchh naatkiya drishy rache bhee gae hai, lekin ve usamen parafaarm naheen kar sake hain.', '-1']
['kamee rah gai hai sirf kahaanee kee, jisakaa jikr pahale bhee kiyaa gayaa.', '-1']
['yahaan tak ki laayak kee dost jhimalee ko takaleef dene se bhee vah baaj naheen aataa.', '-1']
['nekee aur badee gadadamadada hone lagatee hai.', '-1']
['is prakriyaa men vah nirmam hotaa jaataa hai.', '-1']
['thodee der ke lie lagata hai ki kahaanee kiradaaron aur ghatanaon ke beech ulajh gaee hai.', '-1']
['yaha

In [0]:
corpus[0]

['kahaanee',
 'ke',
 'abhaav',
 'me',
 'unake',
 'vyaktigat',
 'prayaas',
 'kaa',
 'prabhaav',
 'kam',
 'ho',
 'jaataa',
 'hai']

In [0]:
def stemming(word):
  stem_word  = re.sub(r'(.{2,}?)([aeiougyn]+$)',r'\1', word)
  return stem_word

In [0]:
#flat_list_kgp = []
#def flat_r_word(word):
#  flat_list_kgp = flat_list
#  flat_list_kgp.remove(word)
  
      
#  return flat_list

In [0]:
def levenstein(word,given_list,lev_index,s_index):
  elist = []
  for i in given_list:
    if word[0] ==i[0]:
      elist.append(i)
    else:
      pass

  pair = {}
  for i in elist:
    lev_dist = edit_distance(word,i)
    if lev_dist<=lev_index:
      pair.update({i:lev_dist})
    
    
  
  if not bool(pair):
    return 42
    
  


  pair2  = {}

  for key, value in sorted(pair.items(), key=lambda item: item[1]):
      pair2.update({key:value})

    
  pair2_list = []
  count2 = 0
  for key in pair2.keys() :
    count2 = count2 +1
    if count2<20:
      
      pair2_list.append(key)
      
        
      
    else:
      pass
  
  
  if not pair2_list:
    return 42

  
  def soundex(word):
     codes = ("bfpv","cgjkqsxz", "dt", "l", "mn", "r")
     soundDict = dict((ch, str(ix+1)) for ix,cod in enumerate(codes) for ch in cod)
     cmap2 = lambda kar: soundDict.get(kar, '9')
     sdx =  ''.join(cmap2(kar) for kar in word.lower())
     sdx2 = word[0].upper() + ''.join(k for k,g in list(groupby(sdx))[1:] if k!='9')
     sdx3 = sdx2[0:4].ljust(4,'0')
     return sdx3


  pair2_list_soundex = {}
  for i in pair2_list:
    pair2_list_soundex.update({i:soundex(i)})

  a = soundex(word)
  a =int(a[1:])

  new_dict = {}
  for i in pair2_list_soundex:
    b=str(pair2_list_soundex.get(i))
    b=int(b[1:])
    new_dict.update({i:b})

  nd = {}
  for i in new_dict:
    if abs(a-new_dict.get(i))<=s_index:
      nd.update({i:abs(a-new_dict.get(i))})
    
    
  if not nd:
    return 42
       
        
         
    

  sorted_x = sorted(nd.items(), key=lambda kv: kv[1])
  import collections
  sorted_dict = collections.OrderedDict(sorted_x)
  lev_word = list(sorted_dict.keys())[0]
 
  return lev_word

In [0]:
def check_list(list,word):
  for i in list:
    if word==i:
      return 1
    else:
      pass

In [0]:
def check_word(word):
  L = 1
  K = 0
  N = 0
  stem_word = 0
  lev_word = 0
  not_found = 0
  
  if check_list(pos_list,word):
    return L,"POS",K,N,stem_word,lev_word,not_found
  elif check_list(neg_list,word):
    return L,"NEG",K,N,stem_word,lev_word,not_found
  elif check_list(stop_list,word):
    return L,"STOP",K,N,stem_word,lev_word,not_found
  elif check_list(kgp_list3,word):
    
    stem_word = stemming(word)
    K = 1
    L = 2
    if check_list(pos_list,stem_word):
      
      return L,"POS",K,N,stem_word,lev_word,not_found
    elif check_list(neg_list,stem_word):
      return L,"NEG",K,N,stem_word,lev_word,not_found
    elif check_list(stop_list,stem_word):
      return L,"STOP",K,N,stem_word,lev_word,not_found
    elif check_list(kgp_list3,stem_word):
      return L,"KGP",K,N,stem_word,lev_word,not_found
    else:
      
      L = 3
      lev_word = levenstein(word,flat_list,5,5)
      if lev_word ==42:
        
        not_found = 1
        return L,"NOT",K,N,stem_word,lev_word,not_found
      
      elif check_list(pos_list,lev_word):
        return L,"POS",K,N,stem_word,lev_word,not_found
      elif check_list(neg_list,lev_word):
        return L,"NEG",K,N,stem_word,lev_word,not_found
      elif check_list(stop_list,lev_word):
        return L,"STOP",K,N,stem_word,lev_word,not_found
      elif check_list(kgp_list3,lev_word):
        return L,"KGP",K,N,stem_word,lev_word,not_found
      else:
        return L,"NOT",K,N,stem_word,lev_word,not_found
  else:
    L = 2
    N = 1
    stem_word = stemming(word)
    if check_list(pos_list,stem_word):
      return L,"POS",K,N,stem_word,lev_word,not_found
    elif check_list(neg_list,stem_word):
      return L,"NEG",K,N,stem_word,lev_word,not_found
    elif check_list(stop_list,stem_word):
      return L,"STOP",K,N,stem_word,lev_word,not_found
    elif check_list(kgp_list3,stem_word):
      return L,"KGP",K,N,stem_word,lev_word,not_found
    else:
     
      L = 3
      lev_word = levenstein(word,flat_list,5,2)
      if lev_word ==42:
        not_found = 1
        return L,"NOt",K,N,stem_word,lev_word,not_found


      elif check_list(pos_list,lev_word):
        return L,"POS",K,N,stem_word,lev_word,not_found
      elif check_list(neg_list,lev_word):
        return L,"NEG",K,N,stem_word,lev_word,not_found
      elif check_list(stop_list,lev_word):
        return L,"STOP",K,N,stem_word,lev_word,not_found
      elif check_list(kgp_list3,lev_word):
        return L,"KGP",K,N,stem_word,lev_word,not_found
      else:
        return L,"NOt",K,N,stem_word,lev_word,not_found


  
  

In [0]:
v = check_word("deshabhakti")

In [0]:
v

(2, 'POS', 0, 1, 'deshabhakt', 0, 0)

In [0]:
print(v)

(2, 'POS', 0, 1, 'deshabhakt', 0, 0)


In [0]:
corpus_copy2 = []
for i in range(len(corpus)):
  corpus_copy = []
  for word in corpus[i]:
    
    v = check_word(word)
    print(word,v)
    if v[1] =="STOP":
      pass

    elif  v[0] == 1 and (v[1] =="POS" or v[1] =="NEG"):
      corpus_copy.append(word)
    elif v[0] == 2 and v[2] == 1 and (v[1] =="POS" or v[1] =="NEG" or v[1] =="KGP"):
      corpus_copy.append(v[4])
    elif v[0] == 3 and v[2] == 1 and (v[1] =="POS" or v[1] =="NEG" or v[1] =="KGP"):
      corpus_copy.append(v[5])

    elif v[0] == 2 and v[3] == 1 and (v[1] =="POS" or v[1] == "NEG" or v[1] =="KGP"):
      corpus_copy.append(v[4])
    elif v[0] == 3 and v[3] == 1 and (v[1] =="POS" or v[1] =="NEG" or v[1] =="KGP"):
      corpus_copy.append(v[5])
    elif v[6]==1:
      corpus_copy.append(word)
    
  corpus_copy = ' '.join(corpus_copy)

  corpus_copy2.append(corpus_copy)
  
  


kahaanee (2, 'KGP', 1, 0, 'kah', 0, 0)
ke (1, 'STOP', 0, 0, 0, 0, 0)
abhaav (1, 'NEG', 0, 0, 0, 0, 0)
me (1, 'STOP', 0, 0, 0, 0, 0)
unake (2, 'KGP', 1, 0, 'unak', 0, 0)
vyaktigat (1, 'POS', 0, 0, 0, 0, 0)
prayaas (3, 'KGP', 0, 1, 'prayaas', 'prakaash', 0)
kaa (2, 'STOP', 1, 0, 'ka', 0, 0)
prabhaav (1, 'POS', 0, 0, 0, 0, 0)
kam (1, 'STOP', 0, 0, 0, 0, 0)
ho (1, 'STOP', 0, 0, 0, 0, 0)
jaataa (2, 'KGP', 1, 0, 'jaat', 0, 0)
hai (1, 'STOP', 0, 0, 0, 0, 0)
nakal (2, 'KGP', 1, 0, 'nakal', 0, 0)
ke (1, 'STOP', 0, 0, 0, 0, 0)
aarop (1, 'NEG', 0, 0, 0, 0, 0)
men (2, 'STOP', 1, 0, 'me', 0, 0)
vahaan (1, 'STOP', 0, 0, 0, 0, 0)
unakee (2, 'KGP', 0, 1, 'unak', 0, 0)
chhantai (3, 'KGP', 0, 1, 'chhant', 'chaanta', 0)
ho (1, 'STOP', 0, 0, 0, 0, 0)
jaatee (2, 'KGP', 1, 0, 'jaat', 0, 0)
hai (1, 'STOP', 0, 0, 0, 0, 0)
usakee (3, 'KGP', 1, 0, 'usak', 'usakee', 0)
vajah (2, 'KGP', 1, 0, 'vajah', 0, 0)
se (1, 'STOP', 0, 0, 0, 0, 0)
jagahnsai (3, 'KGP', 0, 1, 'jagahns', 'jagaunga', 0)
bhee (3, 'KGP', 1, 0, 'b

In [0]:
corpus_copy2[0]
with open("/content/drive/My Drive/Hinglish/unbiased_reviews_processed.csv", 'w', newline='') as myfile:
     wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
     wr.writerow(corpus_copy2)

In [0]:
len(corpus_copy2)

1100

In [0]:
corpus_copy2[11]

'thod der lagat kah kirdaar ghatanaon beech ulajh ga'

In [0]:
import nltk  
import numpy as np  
import random  
import string

import bs4 as bs  
import urllib.request  
import re 
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [0]:
wordfreq = {}  
for sentence in corpus_copy2:  
    tokens = nltk.word_tokenize(sentence)
    for token in tokens:
        if token not in wordfreq.keys():
            wordfreq[token] = 1
        else:
            wordfreq[token] += 1

In [0]:
len(wordfreq)

2505

In [0]:
import heapq  
most_freq = heapq.nlargest(2000, wordfreq, key=wordfreq.get)

In [0]:
most_freq

['philm',
 'bhee',
 'kirdaar',
 'unak',
 'jaat',
 'ga',
 'karat',
 'kah',
 'philmon',
 'rah',
 'vah',
 'ba',
 'kalakaar',
 'nirdosh',
 'darshakon',
 'det',
 'sakat',
 'abh',
 'hind',
 'koshish',
 'lagat',
 'drshyon',
 'drshy',
 'khaan',
 'kaam',
 'paat',
 'hot',
 'baat',
 'unhen',
 'pahal',
 'aat',
 'ham',
 'samay',
 'bhonk',
 'achchhee',
 'phir',
 'sangeet',
 'prabhaav',
 'kamajor',
 'sanvaad',
 'ra',
 'khaas',
 'tareeq',
 'roop',
 'lachak',
 'rahat',
 'baavajood',
 'sabh',
 'nibh',
 'geet',
 'usakee',
 'mehanat',
 'dekhat',
 'philmen',
 'la',
 'ehsaan',
 'vajah',
 'beech',
 'isake',
 'prabhaavit',
 'iktiyaar',
 'najar',
 'kapoor',
 'bhaav',
 'chitram',
 'charitram',
 'kamee',
 'badh',
 'sahee',
 'usake',
 'adhik',
 'isalie',
 'saphal',
 'pesh',
 'parde',
 'kaar',
 'poor',
 'samajh',
 'prem',
 'sharmai',
 'daang',
 'romaanch',
 'chhot',
 'shole',
 'daraaz',
 'dhyaan',
 'prasann',
 'abhinav',
 'saajid',
 'prabhaavashaalee',
 'patakatha',
 'salam',
 'ch',
 'saal',
 'sudhaaran',
 'sinema

In [0]:
len(most_freq)

2000

In [0]:
sentence_vectors = []  
for sentence in corpus_copy2:  
    sentence_tokens = nltk.word_tokenize(sentence)
    sent_vec = []
    for token in most_freq:
        if token in sentence_tokens:
            sent_vec.append(1)
        else:
            sent_vec.append(0)
    sentence_vectors.append(sent_vec)

In [0]:
sentence_vectors = np.asarray(sentence_vectors)  

In [0]:
sentence_vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0]])

In [0]:
dataset3 = pd.read_csv("/content/drive/My Drive/Hinglish/unbiased_reviews.csv")
X = sentence_vectors
y = dataset3.iloc[:, 1].values

In [0]:
y

array([-1, -1, -1, ...,  1,  1,  1])

In [0]:
 from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.10, random_state = 0)

In [0]:
len(y_test)

110

In [0]:
import sklearn

In [0]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [0]:
cm
#Naive Bayes accuracy 59.09%

array([[14, 35],
       [10, 51]])

In [0]:

def premat(cm):
  accuracy = (cm[0][0]+cm[1][1])/(cm[0][0]+cm[1][1]+cm[0][1]+cm[1][0])
  print("accuracy", accuracy)
  precision = cm[1][1]/(cm[1][1]+cm[0][1])
  print("precision", precision)
  recall = cm[1][1]/(cm[1][1]+cm[1][0])
  print("recall",recall)
  f1 = 2*precision*recall/(precision+recall)
  print("f1 score ",f1)
  
premat(cm)

accuracy 0.5909090909090909
precision 0.5930232558139535
recall 0.8360655737704918
f1 score  0.6938775510204083


In [0]:

from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(criterion = 'entropy').fit(X_train,y_train)

prediction = tree.predict(X_test)

print("The prediction accuracy is: ",tree.score(X_test,y_test)*100,"%")

The prediction accuracy is:  64.54545454545455 %


In [0]:
prediction

array([ 1, -1, -1,  1,  1, -1,  1, -1,  1, -1,  1,  1, -1,  1, -1,  1,  1,
        1, -1, -1,  1,  1,  1,  1,  1,  1, -1, -1,  1,  1,  1,  1,  1, -1,
        1,  1,  1, -1,  1, -1,  1,  1,  1, -1,  1,  1, -1, -1,  1,  1,  1,
        1,  1,  1,  1, -1, -1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,
        1, -1,  1, -1, -1, -1, -1,  1,  1, -1,  1,  1, -1, -1,  1, -1,  1,
        1, -1,  1, -1, -1,  1, -1, -1, -1,  1,  1, -1,  1, -1, -1, -1, -1,
        1,  1,  1,  1,  1, -1,  1, -1])

In [0]:
y_test

array([-1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,
        1, -1, -1, -1,  1, -1,  1, -1,  1,  1, -1,  1,  1, -1,  1,  1, -1,
        1,  1,  1,  1,  1, -1, -1, -1, -1,  1,  1, -1,  1,  1,  1, -1,  1,
        1, -1, -1,  1, -1, -1,  1,  1,  1,  1, -1, -1,  1, -1,  1,  1,  1,
       -1, -1,  1,  1, -1, -1, -1,  1,  1, -1, -1, -1, -1, -1,  1, -1, -1,
        1, -1, -1, -1, -1,  1,  1, -1, -1,  1,  1,  1,  1, -1,  1, -1, -1,
        1, -1,  1,  1,  1,  1, -1,  1])

In [0]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)


y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [0]:
premat(cm)
#Logistic Regression accuracy 70%

accuracy 0.7
precision 0.6944444444444444
recall 0.819672131147541
f1 score  0.7518796992481204


In [0]:
y_pred

In [0]:
y_test

In [0]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm
#SVM accuracy 70.90%

In [0]:
premat(cm)

accuracy 0.7090909090909091
precision 0.704225352112676
recall 0.819672131147541
f1 score  0.7575757575757576


In [0]:
y_pred

In [0]:
y_test

In [0]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

cm
# Random Forest Accuracy 66.36%

In [0]:
premat(cm)

accuracy 0.6636363636363637
precision 0.6578947368421053
recall 0.819672131147541
f1 score  0.7299270072992702


In [0]:

dataset4 = pd.read_csv("/content/drive/My Drive/Hinglish/new_for_ann.csv")
X = dataset4.iloc[:,0].values
y = dataset4.iloc[:,1].values
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)



In [0]:
X_test

In [0]:
import keras
from keras.models import Sequential
from keras.layers import Dense
classifier = Sequential()

classifier.add(Dense(units = 5, kernel_initializer = 'uniform', activation = 'relu', input_dim = 1))


classifier.add(Dense(units = 5, kernel_initializer = 'uniform', activation = 'relu'))


classifier.add(Dense(units = 5, kernel_initializer = 'uniform', activation = 'relu'))


classifier.add(Dense(units = 1, kernel_initializer = 'uniform' ,activation = 'sigmoid'))

In [0]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [0]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)
y_pred = classifier.predict(X_test)